### ISSUE TITLE
Alternative URL going to the wrong page

### ISSUE THREAD

**Issue by nddejong** [sebduggan/muraURLTools#35]
We are seeing this quite frequently and it is driving our users nuts.  To replicate the issue I created a brand new Mura site using Railo 4.1, Mura 6.1, and the latest zip of URL Tools. I created two test pages directly under home with alt url of itf and itfa.  I then created a folder directly under home and put a test page in that folder with an alt url of it.  When I go to the home page and put /it in the url it sends me to the test page with the alt url of itf instead of the page inside the folder that it was supposed to go to.

Thanks,
Nathan

**Comment by jeaguilar** [comment]
I think this is because of the following in eventHandler.cfc, getURLQuery:

`tclassextenddata.attributeValue #likeCi# <cfqueryparam cfsqltype="cf_sql_varchar" value="%#arguments.currentFilenameAdjusted#%">`

The LIKE and % operators are used because the Alternate URL List can have multiple line delimited values.

If you know you are never going to use multiple alternate urls in a single document and you have this type of situation, you can change that line to:

`tclassextenddata.attributeValue = <cfqueryparam cfsqltype="cf_sql_varchar" value="#arguments.currentFilenameAdjusted#">`

A better solution which maintains the "multiple line delimited values" functionality would require looping over the results of the query (if multiple results were returned) and then searching within the results for alternateURLList.

**Comment by jeaguilar** [comment]
This might be that "better solution"

In eventHandler.cfc, getURLQuery replace:
		
		<cfreturn rs />

With:

		<cfif rs.recordCount GT 1>
			<cfloop query="rs">
				<cfif ArrayFindNoCase(listToArray(rs.alternateURLList, Chr(10)), arguments.currentFilenameAdjusted) != 0 || ArrayFindNoCase(listToArray(rs.alternateURLList, Chr(13)), arguments.currentFilenameAdjusted) != 0>
					<cfset var newRs = queryNew("contentID,filename,redirectType,overwriteTag,overwriteCategory,alternateURLList")>
					<cfset QueryAddRow(newRs, 1)>
					<cfset QuerySetCell(newRs, "contentID", rs.contentID, 1)>
					<cfset QuerySetCell(newRs, "filename", rs.filename, 1)>
					<cfset QuerySetCell(newRs, "redirectType", rs.redirectType, 1)>
					<cfset QuerySetCell(newRs, "overwriteTag", rs.overwriteTag, 1)>
					<cfset QuerySetCell(newRs, "overwriteCategory", rs.overwriteCategory, 1)>
					<cfset QuerySetCell(newRs, "alternateURLList", rs.alternateURLList, 1)>
					<cfset rs = newRs>
					<cfbreak>
				</cfif>
			</cfloop>
		</cfif>

		<cfreturn rs />

Not sure why I have to use both Chr(10) and Chr(13) as a delimiter but I haven't looked into it that closely either.

**Comment by sebduggan** [comment]
Should be fixed via Pull Request #32
